Map tree
pavlo-onyshchak/cppTasks pull request #4
Opened 2019-11-04 22:10 UTC by pavlo-onyshchak

2019-11-05 08:47 UTC, OlehOnyshchak requested changes
Looks really good in general. Mostly requesting tiny changes.

ALso, please don't commit all generated files like exe, obj. pdb etc,

2019-11-05 08:47 UTC, OlehOnyshchak commented on Map/Map/Map.h
> +    Node* FindMax(Node* root);
keep consistent formatting

2019-11-05 08:47 UTC, OlehOnyshchak commented on Map/Map/Map.h
> +    pair<int, string> _data;
It's better to put Node definition into Map's private block, so that you can use `key_val data`.
Also, from Google code convention, data members from struct shouldn't be underscored, i.e. it should be `data`

2019-11-05 08:47 UTC, OlehOnyshchak commented on Map/Map/Map.cpp
> +        if (!node)
That check should be on line 9, in condition for `while`. Because currently, it will crash when `_root == nullptr`

2019-11-05 08:47 UTC, OlehOnyshchak commented on Map/Map/Map.cpp
> +    return it;
Just write `return {node}`  or at least `return Iterator(node)`. The same everywhere.

2019-11-05 08:47 UTC, OlehOnyshchak commented on Map/Map/Map.cpp
> +            leaf->_data = data;
Does it work to write simpy `auto leaf = new Node{data};`?

2019-11-05 08:47 UTC, OlehOnyshchak commented on Map/Map/Map.cpp
> +void Map::insert(const key_val& data, Node* node)
This looks good but has a lot of data duplication. Think about organizing code in the following way:
```cpp
if (data.key == node->key) {
  // replace
  returnl
}

auto& child = (data.key < node->key ? node->_left : node->_right;
child =  new Node{data}'
```

2019-11-05 08:47 UTC, OlehOnyshchak commented on Map/Map/Map.cpp
> +        insert(data,_root);
Nice separation of logic into two functions

2019-11-05 08:47 UTC, OlehOnyshchak commented on Map/Map/Map.cpp
> +    auto size = init.size();
Redundant variable, please remove

2019-11-05 08:47 UTC, OlehOnyshchak commented on Map/Map/Map.cpp
> +    for (auto it = init.begin(); it != init.end(); it++)
Mostly style, but try to do `++it` in a loop as a habit, it's more efficient.
But if you prefer this way, it's OK

2019-11-05 08:47 UTC, OlehOnyshchak commented on Map/Map/Map.cpp
> +    _size++;
Why do you do this? You shouldn't pass values as internal fields, here you should return the size directly.

2019-11-05 08:47 UTC, OlehOnyshchak commented on Map/Map/Map.cpp
> +    return _size;
If you call Map::size two times in a row, it will output incorrect size

2019-11-05 08:47 UTC, OlehOnyshchak commented on Map/Map/Map.cpp
> +    return _root; //it's work correct, but doesn't shure if code style is ok
Yeah, probably better would be to write explicitly `return _root != nullptr;`

2019-11-05 08:47 UTC, OlehOnyshchak commented on Map/Map/Map.cpp
> +    while (root->_right != nullptr)
Nice!

2019-11-05 08:47 UTC, OlehOnyshchak commented on Map/Map/Map.cpp
> +
extra new line

2019-11-05 08:47 UTC, OlehOnyshchak commented on Map/Map/Map.cpp
> +    show(_root);
That separation into different function might be too much. You can just copy-paste lines 183-189 here directly and it will work just fine.

That's better because you don't have any high-level logic here, just calling another function. While in insert method that was nice, since you had extra logic of checking _root.

2019-11-05 08:47 UTC, OlehOnyshchak commented on Map/Map/Map.cpp
> +    if (node == nullptr)
you can write here `auto [node_key, node_val] = node->_data`  and use those variables below to make the code more readable. 

But it's subjective for style. Just saying to make sure you know about it

2019-11-05 08:47 UTC, OlehOnyshchak commented on Map/Map/Map.cpp
> +            node = nullptr;
It's OK for this iteration, but when you made sure everything works properly - we should change the new-delete logic with std::shared_ptr

2019-11-05 08:47 UTC, OlehOnyshchak commented on Map/Map/Map.cpp
> +Node* Map::erase(Node* node, key data)
A lot of logic here so didn't check everything manually. But please, add test cases, as you did before, and then it would be clear whether it works.

Actually, why have you deleted your test case? You should have just change imolementation and rerun tests. But also, I would like you to make test coverage bigger than it was

2019-11-05 22:40 UTC, pavlo-onyshchak commented on Map/Map/Map.cpp
> +        if (!node)
if i will move it to the line 9,it will be exception in while condition(e.q I want to find the element which doesnt exist in the tree(9000),it will go to the right end of tree and when it cross al the existed node,it will equal to nullptr,and when the new while will start ,it will compare key with nullptr node and this will cause an exception here,thats why i move the check to this line

2019-11-06 13:40 UTC, pavlo-onyshchak commented on Map/Map/Map.cpp
> +    show(_root);
But the users dont know about Node,thats why i separated this logic into 2 function.

2019-11-07 09:35 UTC, OlehOnyshchak commented on Map/Map/Map.cpp
> +        if (!node)
Sorry for the confusion. I meant to delete this check here and rewrite `while` condition as `while (node && key != node->_data.first`

2019-11-07 09:37 UTC, OlehOnyshchak commented on List/List/Main.cpp
> +void main()
Why do you have a List it Map branch? It shouldn't be here. Now you have List and Bit operations here

2019-11-07 09:38 UTC, OlehOnyshchak commented on Map/Map/Iterator.h
> +class Iterator
Please, add `operator*` and also increment and decrement operators to Iterator

2019-11-07 09:39 UTC, OlehOnyshchak commented on Map/Map/Iterator.h
> +    pair<int, string>* data;
should be `Map::key_val`

2019-11-07 09:42 UTC, OlehOnyshchak commented on Map/Map/Map.cpp
> +
extra line

2019-11-07 09:43 UTC, OlehOnyshchak commented on Map/Map/Map.cpp
> +void Map::insert(const key_val& data, shared_ptr<node> node)
here it's better just to make it `node* node`. We don't need to extend lifetime of the node in this function and copying shared pointers is expensive. But for this time - it's optional for you to implement. Just make sure you understand

2019-11-07 09:46 UTC, OlehOnyshchak commented on Map/Map/Map.cpp
> +size_t Map::traversal(shared_ptr<node> node,size_t& size)
Why do you need this parameter `size` here? Just return it, don't pass it from outside

2019-11-07 09:48 UTC, OlehOnyshchak commented on Map/Map/Map.cpp
> +    return size() == 0;
nice

2019-11-07 09:51 UTC, OlehOnyshchak commented on Map/Map/Map.cpp
> +    auto my_map = Map({ {100,"a"},{50,"b"},{30,"c"},{150,"d"},{130,"d"},{110,"d"},{140,"d"},{200,"d"} });
move this init list in one variable, that is:
```cpp
auto vals = { {100,"a"},{50,"b"},{30,"c"},{150,"d"},{130,"d"},{110,"d"},{140,"d"},{200,"d"} };
auto my_map = Map{vals};
auto stl_map = map<int, string>{vals};
```

2019-11-07 09:57 UTC, OlehOnyshchak commented on Map/Map/Map.cpp
> +    vector<int> vec{ 100,50,30,150,130,110,140,200 };
Create `vec` from `vals` defined in the above comment. That is, something like:
```cpp
auto vec = vector<int>{};
std::transform(vals.begin(), vals.end(), std::back_inserter(vec), [](key_val v) { return v.first; });
```

2019-11-07 09:58 UTC, OlehOnyshchak commented on Map/Map/Map.cpp
> +bool Map::test()
Pretty good test, I love it

2019-11-07 10:00 UTC, OlehOnyshchak commented on Map/Map/Map.h
> +   private:
Nice. It's a style matter but I love separating data members and data functions with another private block, makes code more readable

2019-11-07 10:00 UTC, OlehOnyshchak commented on Map/Map/Map.h
> +    pair<string, int> _map_data;
Why do you need this variable?

2019-11-07 10:02 UTC, OlehOnyshchak approved these changes
Good work, looks really good! Just fix a few minor comments I left (the most significant is size parameter) and you good to merge changes

2019-11-10 14:47 UTC, pavlo-onyshchak commented on Map/Map/Map.cpp
> +void Map::insert(const key_val& data, shared_ptr<node> node)
In this case I think it's impossible to rewrite for the node* node,because my Map::_root is shared_ptr<node>

2019-11-10 21:33 UTC, merged